name: lympclear
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-image
  - nibabel
  - simpleitk
  - pydicom
  - imageio
  - tqdm
  - pyyaml
  - matplotlib
  - pytest
  - pip:
      - nnunetv2
